### ISSUE TITLE
How to update cache without changing url?

### ISSUE THREAD

**Issue by ed5on** [marcglasberg/network_to_file_image#16]
1. The image is downloaded in cache from the url.
2. The image changes on the server but not the url.
Is it possible to update the cache with the new image ?.

**Comment by marcglasberg** [comment]
You can't really know if the image changed on the server because it never actually goes to the server again if the image is already in the local disk. You can achieve what you want if you delete the image from local disk yourself.

If you want to have expiring images you probably need another widget. The network_to_file_image is meant for images you want to download. Not images that change. In that sense, the local copy is not a cache.
