### ISSUE TITLE
Enhancement Request if I'm understanding the methodology correctly

### ISSUE THREAD

**Issue by jodymac** [marcglasberg/network_to_file_image#26]
Does this package only check the filename or does it check details of the file to determine if it needs to be downloaded from the network or served from the local directory?

if it only checks the filename, then...

Would it be possible to check for created date as well on image file to determine whether to download or keep serving from the local directory?

My app allows clients to upload a logo and an image and we give them the file names to upload based on their geographic location and database id.  My dilemma is if they change either file, it will continue to serve the local copy rather than replaced file on the webserver source.

If this can't be done this way, then my options are...
1.  Allow the users to specify their own name which might create naming conflicts and will definitely increase tech support.
2. Periodically clear the directory the local images are stored in which defeats my intention of keeping network data to a minimum by only downloading updated json data.

**Comment by marcglasberg** [comment]
The idea of this package is really to download the images. It's seems you want a cache of images, which can be evicted from the cache according to some policy. There are some other packages out there that implement what you want.

While I plan one day to improve this widget to allow for eviction policies, that's not its original purpose. And I feel I won't have the time to change that in the foreseeable future.

I'd also suggest you could periodically clear only the images that have been created more than x days ago, instead of the whole directory. That would achieve your desired effect.
