### ISSUE TITLE
Image can not be loaded after errorBuilder was used

### ISSUE THREAD

**Issue by PandaGeek1024** [marcglasberg/network_to_file_image#27]
Problem:
I use errorBuilder from Image to handle the exceptional case that url can not be loaded, e.g. no network. The error widget is displayed properly, but once I quit to the previous page, turn on network and come back again, it is still showing the error widget. It seems like _loadAsync() does not get called. Any idea what's going on?

btw, I found this similar [issue](https://github.com/flutter/flutter/pull/65180) for Image.network(), but looks like it is fixed.

My code:
```
Image(
  image: NetworkToFileImage(
      url: imageUrl,
      file: file),
  errorBuilder: (context, error, stackTrace) {
    return AbsorbPointer(child: Text('Download image failed,'));
  },
);
```

**Comment by marcglasberg** [comment]
I'll have a look at this as soon as I can upgrade to Flutter 2.5, within the next 3 weeks, I guess.

**Comment by hm86z** [comment]
Hello , Is this problem has been fixed?

**Comment by hm86z** [comment]
I have the same problem when I get an error that is not due to the errorBuilder or  processError,
the widget just stays white..

**Comment by marcglasberg** [comment]
I believe this is fixed for:

    network_to_file_image: ^3.0.3

If you now run the main example there is a "Rebuild image widget" button.

This is the manual test: Turn off the internet (turn on airplane mode) before running the app, you'll first get a `Download image failed` message. Then, turn on the internet the press the button to rebuild. It will show the image.

Note: To do the manual test, make sure the image is not already saved on disk. Otherwise it will not hit the internet anyway. You can make sure of this by changing the name of the file you're saving to. For example, from `fileFromDocsDir("flutter.png")` to `fileFromDocsDir("xxx.png")`.

@PandaGeek1024 @hm86z Could you please confirm this is fixed for you, and if so close the issue?

**Comment by hm86z** [comment]
Thanks for your reply, it works as you said, but why does the image remain white and the loading  image in loadingBuilder does not appear until Connection timed out occure and then errorBuilder appear.

in another meaning: I want to show  loadingBuilder  until errorBuilder appear.


this my code:

 ```
Image(
                key: ValueKey(_countImageKey),
                fit: BoxFit.cover,
                height: height,
                width: width,

                image:

                NetworkToFileImage(
                  url: _url ,
                  file:_photosDir,
                  debug: true,
                ),

                loadingBuilder:(context, child, loadingProgress) {
                  if (loadingProgress == null) return child;
                  return
                    Image.asset('images/loading_image.png' ,
                      fit:BoxFit.cover,
                      height:  height,
                      width:     width  ,
                    );


                },

                errorBuilder:  (context, error, stackTrace){
                  return   onErr();
                },
              );
```

**Comment by marcglasberg** [comment]
@hm86z This is an entirely different problem. I am closing this issue, so please can you open a new one for the `loadingBuilder`? I'll look into it. Thanks!
